
name: CI
on: [push]
jobs:
  linux-server:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo 
          git --version
          echo
          whoami
          echo
          free -m
          echo
          uname -r 


  windows-Server: 
    runs-on: ubuntu-latest
    needs: ["linux-server"]
    steps:
      - name: powershell
        run: Get-ScriptAnalyzerRule
        shell: pwsh


      
                    